export const ADD_PASSENGER_TO_BOOKING = "ADD_PASSENGER_TO_BOOKING";
export const REMOVE_PASSENGER_FROM_BOOKING = "REMOVE_PASSENGER_FROM_BOOKING";
export const ADD_PAYMENT_METHOD = "ADD_PAYMENT_METHOD";
export const REMOVE_PAYMENT_METHOD = "REMOVE_PAYMENT_METHOD";
export const ADD_CAB_TO_DESTINATION = "ADD_CAB_TO_DESTINATION";
